# 服务注册中心
eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
# 服务间调用
feign:
    hystrix:
        enabled: false
# 日志
logging:
    level:
        io:
            seata: info
# 数据持久层
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.fly.demo.entity
server:
    port: 8180
spring:
    application:
        name: order-server
    cloud:
        alibaba:
            seata:
               # 事务组，seata server，seata client都要保持一致
                tx-service-group: fsp_tx_group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root123#
        url: jdbc:mysql://localhost:3306/seata_order
        username: root
